// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema/anchor.proto

package anchor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IslandType int32

const (
	IslandType_btc IslandType = 0
	IslandType_eth IslandType = 1
	IslandType_nem IslandType = 2
)

var IslandType_name = map[int32]string{
	0: "btc",
	1: "eth",
	2: "nem",
}

var IslandType_value = map[string]int32{
	"btc": 0,
	"eth": 1,
	"nem": 2,
}

func (x IslandType) String() string {
	return proto.EnumName(IslandType_name, int32(x))
}

func (IslandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b6f1773bc5554a7f, []int{0}
}

type Anchor struct {
	Description          string     `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Version              string     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Target               IslandType `protobuf:"varint,3,opt,name=target,proto3,enum=anchor.IslandType" json:"target,omitempty"`
	Locks                []*Lock    `protobuf:"bytes,4,rep,name=locks,proto3" json:"locks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Anchor) Reset()         { *m = Anchor{} }
func (m *Anchor) String() string { return proto.CompactTextString(m) }
func (*Anchor) ProtoMessage()    {}
func (*Anchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6f1773bc5554a7f, []int{0}
}

func (m *Anchor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anchor.Unmarshal(m, b)
}
func (m *Anchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anchor.Marshal(b, m, deterministic)
}
func (m *Anchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anchor.Merge(m, src)
}
func (m *Anchor) XXX_Size() int {
	return xxx_messageInfo_Anchor.Size(m)
}
func (m *Anchor) XXX_DiscardUnknown() {
	xxx_messageInfo_Anchor.DiscardUnknown(m)
}

var xxx_messageInfo_Anchor proto.InternalMessageInfo

func (m *Anchor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Anchor) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Anchor) GetTarget() IslandType {
	if m != nil {
		return m.Target
	}
	return IslandType_btc
}

func (m *Anchor) GetLocks() []*Lock {
	if m != nil {
		return m.Locks
	}
	return nil
}

type Lock struct {
	Type                 IslandType `protobuf:"varint,1,opt,name=type,proto3,enum=anchor.IslandType" json:"type,omitempty"`
	Version              string     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Block                *Block     `protobuf:"bytes,4,opt,name=block,proto3" json:"block,omitempty"`
	LastKnownPosition    string     `protobuf:"bytes,5,opt,name=lastKnownPosition,proto3" json:"lastKnownPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Lock) Reset()         { *m = Lock{} }
func (m *Lock) String() string { return proto.CompactTextString(m) }
func (*Lock) ProtoMessage()    {}
func (*Lock) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6f1773bc5554a7f, []int{1}
}

func (m *Lock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lock.Unmarshal(m, b)
}
func (m *Lock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lock.Marshal(b, m, deterministic)
}
func (m *Lock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lock.Merge(m, src)
}
func (m *Lock) XXX_Size() int {
	return xxx_messageInfo_Lock.Size(m)
}
func (m *Lock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lock.DiscardUnknown(m)
}

var xxx_messageInfo_Lock proto.InternalMessageInfo

func (m *Lock) GetType() IslandType {
	if m != nil {
		return m.Type
	}
	return IslandType_btc
}

func (m *Lock) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Lock) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lock) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Lock) GetLastKnownPosition() string {
	if m != nil {
		return m.LastKnownPosition
	}
	return ""
}

type Block struct {
	Height               string   `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Uri                  []string `protobuf:"bytes,4,rep,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6f1773bc5554a7f, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Block) GetUri() []string {
	if m != nil {
		return m.Uri
	}
	return nil
}

func init() {
	proto.RegisterEnum("anchor.IslandType", IslandType_name, IslandType_value)
	proto.RegisterType((*Anchor)(nil), "anchor.Anchor")
	proto.RegisterType((*Lock)(nil), "anchor.Lock")
	proto.RegisterType((*Block)(nil), "anchor.Block")
}

func init() { proto.RegisterFile("schema/anchor.proto", fileDescriptor_b6f1773bc5554a7f) }

var fileDescriptor_b6f1773bc5554a7f = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0x6d, 0xfe, 0x94, 0x4c, 0x3f, 0x25, 0x8e, 0x20, 0xb9, 0xf0, 0x22, 0x44, 0xd0,
	0x50, 0xa4, 0x42, 0x7d, 0x02, 0xbd, 0x13, 0xbd, 0x90, 0xe0, 0x0b, 0x6c, 0xb7, 0x4b, 0x37, 0x34,
	0xd9, 0x0d, 0xd9, 0x55, 0xe9, 0x7b, 0xf8, 0x1e, 0xbe, 0xa2, 0xec, 0x34, 0xa1, 0x82, 0xe2, 0xdd,
	0x39, 0x73, 0x26, 0x33, 0xbf, 0xcc, 0xc2, 0xa9, 0x15, 0x4a, 0xb6, 0xfc, 0x86, 0x6b, 0xa1, 0x4c,
	0xbf, 0xe8, 0x7a, 0xe3, 0x0c, 0xc6, 0x7b, 0x57, 0x7c, 0x30, 0x88, 0xef, 0x48, 0x62, 0x0e, 0xb3,
	0xb5, 0xb4, 0xa2, 0xaf, 0x3b, 0x57, 0x1b, 0x9d, 0xb1, 0x9c, 0x95, 0x49, 0xf5, 0xbd, 0x84, 0x19,
	0x4c, 0xdf, 0x64, 0x6f, 0x7d, 0x3a, 0xa1, 0x74, 0xb4, 0x38, 0x87, 0xd8, 0xf1, 0x7e, 0x23, 0x5d,
	0x16, 0xe4, 0xac, 0x3c, 0x5e, 0xe2, 0x62, 0xd8, 0xf6, 0x60, 0x1b, 0xae, 0xd7, 0x2f, 0xbb, 0x4e,
	0x56, 0x43, 0x07, 0x16, 0x10, 0x35, 0x46, 0x6c, 0x6d, 0x16, 0xe6, 0x41, 0x39, 0x5b, 0xfe, 0x1f,
	0x5b, 0x9f, 0x8c, 0xd8, 0x56, 0xfb, 0xa8, 0xf8, 0x64, 0x10, 0x7a, 0x8f, 0x97, 0x10, 0xba, 0x5d,
	0x27, 0x89, 0xe6, 0xf7, 0xb1, 0x94, 0xff, 0x81, 0x86, 0x10, 0x6a, 0xde, 0x4a, 0x02, 0x4b, 0x2a,
	0xd2, 0x78, 0x01, 0xd1, 0xca, 0x2f, 0xca, 0xc2, 0x9c, 0x95, 0xb3, 0xe5, 0xd1, 0x38, 0xf6, 0xbe,
	0x21, 0x06, 0xca, 0xf0, 0x1a, 0x4e, 0x1a, 0x6e, 0xdd, 0xa3, 0x36, 0xef, 0xfa, 0xd9, 0xd8, 0x9a,
	0xae, 0x12, 0xd1, 0x94, 0x9f, 0x41, 0x21, 0x20, 0xa2, 0xaf, 0xf1, 0x0c, 0x62, 0x25, 0xeb, 0x8d,
	0x72, 0xc3, 0x05, 0x07, 0xe7, 0x39, 0x14, 0xb7, 0x6a, 0xc0, 0x23, 0x8d, 0xe7, 0x90, 0xb8, 0xba,
	0x95, 0xd6, 0xf1, 0xb6, 0x1b, 0x00, 0x0f, 0x05, 0x4c, 0x21, 0x78, 0xed, 0x6b, 0x3a, 0x53, 0x52,
	0x79, 0x39, 0xbf, 0x02, 0x38, 0xfc, 0x39, 0x4e, 0x21, 0x58, 0x39, 0x91, 0xfe, 0xf3, 0x42, 0x3a,
	0x95, 0x32, 0x2f, 0xb4, 0x6c, 0xd3, 0xc9, 0x2a, 0xa6, 0x57, 0xbe, 0xfd, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0x0d, 0x90, 0x09, 0xfc, 0x01, 0x00, 0x00,
}
